
import React, { useState, useEffect } from 'react';
import { FileUpload } from './components/FileUpload';
import { SceneCard } from './components/SceneCard';
import { MangaPage, Scene, AspectRatio, GeneratedImage } from './types';
import { explainMangaChunk, generateMangaImage } from './services/geminiService';
import { Sparkles, Loader2, Play, BookOpen, Film, AlertCircle, Download, RotateCcw, Image as ImageIcon, Layout, Key, ExternalLink, ChevronRight, Share2, FileText, ListMusic, Layers, Zap, ArrowRight, Github, Copy } from 'lucide-react';

const ASPECT_RATIOS: { value: AspectRatio; label: string; icon: string }[] = [
  { value: '1:1', label: 'Square', icon: '▢' },
  { value: '4:3', label: 'Classic', icon: '▭' },
  { value: '3:4', label: 'Poster', icon: '▯' },
  { value: '16:9', label: 'Video', icon: '▬' },
  { value: '9:16', label: 'Reels', icon: '▮' },
  { value: '3:2', label: 'Photo', icon: '▭' },
  { value: '2:3', label: 'Book', icon: '▯' },
  { value: '21:9', label: 'Cinema', icon: '▬▬' },
];

const CHUNK_SIZE = 10;

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'explainer' | 'visualizer'>('explainer');
  const [pages, setPages] = useState<MangaPage[]>([]);
  const [scenes, setScenes] = useState<Scene[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [genProgress, setGenProgress] = useState({ current: 0, total: 0 });
  const [error, setError] = useState<string | null>(null);

  // Visualizer state
  const [prompt, setPrompt] = useState('');
  const [selectedRatio, setSelectedRatio] = useState<AspectRatio>('1:1');
  const [generatedImages, setGeneratedImages] = useState<GeneratedImage[]>([]);
  const [isApiKeySelected, setIsApiKeySelected] = useState(false);

  useEffect(() => {
    const checkKey = async () => {
      const hasKey = await (window as any).aistudio.hasSelectedApiKey();
      setIsApiKeySelected(hasKey);
    };
    checkKey();
  }, []);

  const handleSelectKey = async () => {
    await (window as any).aistudio.openSelectKey();
    setIsApiKeySelected(true);
  };

  const handleUpload = (newPages: MangaPage[]) => {
    setPages(newPages);
    setError(null);
  };

  const handleRemove = (index: number) => {
    setPages(prev => prev.filter((_, i) => i !== index));
  };

  const generateExplanation = async () => {
    if (pages.length === 0) {
      setError("Please upload a manga PDF or some panels first.");
      return;
    }

    setIsGenerating(true);
    setError(null);
    setScenes([]);
    
    const totalChunks = Math.ceil(pages.length / CHUNK_SIZE);
    setGenProgress({ current: 0, total: totalChunks });

    try {
      let storyContext = "";
      let allScenes: Scene[] = [];

      for (let i = 0; i < totalChunks; i++) {
        setGenProgress(prev => ({ ...prev, current: i + 1 }));
        
        const start = i * CHUNK_SIZE;
        const end = Math.min(start + CHUNK_SIZE, pages.length);
        const chunkImages = pages.slice(start, end).map(p => p.preview);

        const { scenes: chunkScenes, currentStoryContext } = await explainMangaChunk(
          chunkImages, 
          start, 
          storyContext
        );

        const adjustedScenes = chunkScenes.map((s, idx) => ({
          ...s,
          id: allScenes.length + idx + 1
        }));

        allScenes = [...allScenes, ...adjustedScenes];
        storyContext = currentStoryContext;
        
        setScenes([...allScenes]);

        if (i === 0) {
          setTimeout(() => {
            document.getElementById('results-section')?.scrollIntoView({ behavior: 'smooth' });
          }, 400);
        }
      }
    } catch (err: any) {
      setError(err.message || "An unexpected error occurred during set analysis.");
    } finally {
      setIsGenerating(false);
      setGenProgress({ current: 0, total: 0 });
    }
  };

  const handleGenerateImage = async () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);
    setError(null);

    try {
      const imageUrl = await generateMangaImage(prompt, selectedRatio);
      setGeneratedImages(prev => [{
        url: imageUrl,
        prompt: prompt,
        aspectRatio: selectedRatio,
        timestamp: Date.now()
      }, ...prev]);
    } catch (err: any) {
      if (err.message === "API_KEY_EXPIRED") {
        setIsApiKeySelected(false);
        setError("Session expired. Please re-authenticate your API key.");
      } else {
        setError(err.message || "Image generation failed.");
      }
    } finally {
      setIsGenerating(false);
    }
  };

  const exportToText = () => {
    if (scenes.length === 0) return;

    const header = `MANGA KATHA MASTER SCRIPT\nGenerated by AI Studio Engine\nTimestamp: ${new Date().toLocaleString()}\n${"=".repeat(50)}\n\n`;
    const body = scenes.map(scene => (
      `[BEAT ${scene.id}] ${scene.title.toUpperCase()}\n` +
      `PANELS: ${scene.pages} | TIMING: ${scene.duration}\n\n` +
      `SCRIPT (HINDI):\n"${scene.voiceOver}"\n\n` +
      `${"-".repeat(50)}`
    )).join('\n\n');

    const blob = new Blob([header + body], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `manga_katha_script_${new Date().getTime()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const copyAllToClipboard = () => {
    const text = scenes.map(scene => (
      `BEAT ${scene.id}: ${scene.title}\nDURATION: ${scene.duration}\nSCRIPT: ${scene.voiceOver}`
    )).join('\n\n');
    navigator.clipboard.writeText(text);
    alert("Full master script copied to clipboard!");
  };

  return (
    <div className="min-h-screen pb-40 selection:bg-indigo-500/30 selection:text-white">
      {/* Dynamic Glow Accents */}
      <div className="fixed top-[-10%] left-[-10%] w-[40%] h-[40%] bg-indigo-600/10 blur-[120px] rounded-full -z-10 animate-pulse"></div>
      <div className="fixed bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-purple-600/10 blur-[120px] rounded-full -z-10 animate-pulse" style={{ animationDelay: '1.5s' }}></div>

      {/* Modern Navigation */}
      <nav className="sticky top-0 z-50 bg-slate-950/80 border-b border-white/5 backdrop-blur-3xl px-6">
        <div className="max-w-7xl mx-auto h-20 flex items-center justify-between">
          <div className="flex items-center gap-4 group cursor-pointer" onClick={() => window.scrollTo({top: 0, behavior: 'smooth'})}>
            <div className="w-12 h-12 bg-gradient-to-br from-indigo-600 to-indigo-700 rounded-2xl flex items-center justify-center shadow-2xl shadow-indigo-600/20 group-hover:scale-105 transition-all duration-500 ring-1 ring-white/10">
              <Film className="w-6 h-6 text-white" />
            </div>
            <div className="hidden sm:block">
              <h1 className="text-2xl font-black tracking-tight text-white flex items-center gap-2">
                Manga Katha <span className="text-[10px] bg-indigo-500/10 text-indigo-400 px-2 py-0.5 rounded-lg font-black uppercase tracking-[0.2em] border border-indigo-500/20">Studio</span>
              </h1>
              <p className="text-[9px] uppercase tracking-[0.3em] text-slate-500 font-black">Professional Production Suite</p>
            </div>
          </div>
          
          <div className="flex items-center gap-1.5 bg-slate-900/60 p-1.5 rounded-2xl border border-white/5 shadow-inner">
            <button 
              onClick={() => setActiveTab('explainer')}
              className={`flex items-center gap-2 px-6 py-2.5 rounded-xl text-sm font-black transition-all duration-300 ${activeTab === 'explainer' ? 'bg-indigo-600 text-white shadow-xl shadow-indigo-600/20 ring-1 ring-white/10' : 'text-slate-500 hover:text-slate-300 hover:bg-slate-800/40'}`}
            >
              <Zap className="w-4 h-4" />
              <span className="hidden md:inline">Story Explainer</span>
              <span className="md:hidden">Story</span>
            </button>
            <button 
              onClick={() => setActiveTab('visualizer')}
              className={`flex items-center gap-2 px-6 py-2.5 rounded-xl text-sm font-black transition-all duration-300 ${activeTab === 'visualizer' ? 'bg-indigo-600 text-white shadow-xl shadow-indigo-600/20 ring-1 ring-white/10' : 'text-slate-500 hover:text-slate-300 hover:bg-slate-800/40'}`}
            >
              <ImageIcon className="w-4 h-4" />
              <span className="hidden md:inline">Art Visualizer</span>
              <span className="md:hidden">Art</span>
            </button>
          </div>

          <div className="flex items-center gap-4">
            <div className="h-8 w-px bg-slate-800 hidden md:block"></div>
            <button className="flex items-center justify-center w-11 h-11 rounded-2xl border border-slate-800 text-slate-400 hover:text-white hover:border-indigo-500/50 hover:bg-indigo-500/10 transition-all">
              <Share2 className="w-4.5 h-4.5" />
            </button>
          </div>
        </div>
      </nav>

      {/* Main Container */}
      <main className="max-w-7xl mx-auto px-6 mt-16 sm:mt-24">
        {activeTab === 'explainer' ? (
          <div className="space-y-24 sm:space-y-32 animate-in fade-in duration-1000">
            {/* Elegant Hero Section */}
            <section className="text-center space-y-10">
              <div className="inline-flex items-center gap-2 px-5 py-2 rounded-full bg-slate-900/80 border border-white/5 text-[10px] font-black uppercase tracking-[0.4em] text-indigo-400 shadow-xl">
                <Sparkles className="w-3.5 h-3.5" />
                Next-Gen Content Creation
              </div>
              <h2 className="text-6xl sm:text-8xl md:text-9xl font-black text-white leading-[0.85] tracking-tighter">
                Storytelling, <br className="hidden sm:block" />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-violet-400 to-indigo-600">Reimagined.</span>
              </h2>
              <p className="text-slate-400 max-w-3xl mx-auto text-xl sm:text-2xl hindi-text leading-relaxed font-light opacity-60 px-4">
                अपनी मंगा फाइलों को विस्तार से समझाएं। 10-10 पैनलों के सेट्स में कहानी का सटीक विश्लेषण और बेहतरीन हिंदी नैरेशन।
              </p>
              <div className="flex justify-center gap-6 pt-4">
                 <button className="flex items-center gap-2 text-xs font-black text-slate-500 hover:text-white transition-all uppercase tracking-widest px-6 py-3 rounded-2xl border border-transparent hover:border-white/5 hover:bg-slate-900">
                   <BookOpen className="w-4 h-4" /> View Guide
                 </button>
              </div>
            </section>

            {/* Workflow Dashboard */}
            <div className="space-y-20">
              {/* Repository Section */}
              <div className="glass-panel rounded-[3.5rem] p-10 sm:p-16 shadow-3xl relative overflow-hidden border border-white/5 bg-slate-900/20 backdrop-blur-xl">
                <div className="absolute top-0 right-0 p-16 opacity-[0.02] -rotate-12 select-none pointer-events-none">
                    <Layers className="w-64 h-64 text-white" />
                </div>
                
                <div className="relative space-y-12">
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
                    <div className="space-y-2">
                      <h3 className="text-3xl font-black text-white uppercase tracking-tight flex items-center gap-4">
                        <div className="w-10 h-10 rounded-xl bg-indigo-600/20 flex items-center justify-center text-indigo-400 border border-indigo-500/20">01</div>
                        Production Assets
                      </h3>
                      <p className="text-xs text-slate-500 font-bold uppercase tracking-[0.3em] pl-14">Import your manga pages to generate script beats</p>
                    </div>
                  </div>
                  
                  <FileUpload pages={pages} onUpload={handleUpload} onRemove={handleRemove} />
                  
                  {/* Global Process Button */}
                  <div className="flex flex-col items-center pt-16 border-t border-white/5">
                    <button
                      onClick={generateExplanation}
                      disabled={isGenerating || pages.length === 0}
                      className={`
                        group relative flex items-center gap-6 px-16 py-7 rounded-[2rem] font-black text-2xl transition-all w-full sm:w-auto justify-center
                        ${isGenerating || pages.length === 0 
                          ? 'bg-slate-800 text-slate-600 cursor-not-allowed border border-white/5 opacity-50' 
                          : 'bg-indigo-600 text-white hover:bg-indigo-500 hover:scale-[1.03] active:scale-95 shadow-[0_30px_60px_-15px_rgba(79,70,229,0.4)] ring-1 ring-white/20'}
                      `}
                    >
                      {isGenerating ? (
                        <div className="flex flex-col items-center gap-2">
                          <div className="flex items-center gap-4">
                             <Loader2 className="w-8 h-8 animate-spin" />
                             Processing Phase {genProgress.current}
                          </div>
                          <div className="text-[10px] font-black text-indigo-200 uppercase tracking-widest opacity-60"> Analyzing Context & Visuals </div>
                        </div>
                      ) : (
                        <>
                          <Zap className="w-8 h-8 group-hover:scale-110 transition-transform fill-white/10" />
                          Initialize Production
                        </>
                      )}
                    </button>
                    
                    {error && (
                      <div className="mt-10 w-full max-w-xl animate-in fade-in slide-in-from-top-4">
                        <div className="flex items-center gap-5 text-red-400 bg-red-400/5 px-8 py-6 rounded-[2.5rem] border border-red-400/20 backdrop-blur-3xl shadow-2xl">
                          <div className="w-12 h-12 rounded-2xl bg-red-400/10 flex items-center justify-center shrink-0">
                            <AlertCircle className="w-6 h-6" />
                          </div>
                          <div className="space-y-1">
                            <p className="font-black text-xs uppercase tracking-widest">Production Error</p>
                            <p className="font-medium text-sm text-red-400/80 leading-relaxed">{error}</p>
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Master Output Section */}
              {scenes.length > 0 && (
                <div id="results-section" className="space-y-16 py-20 animate-in slide-in-from-bottom-20 duration-1000">
                  <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 border-b border-white/5 pb-10">
                    <div className="space-y-3">
                      <div className="flex items-center gap-4">
                        <div className="w-12 h-12 rounded-2xl bg-indigo-600/10 flex items-center justify-center text-indigo-400 border border-indigo-500/20">02</div>
                        <h3 className="text-4xl font-black text-white tracking-tight">Script Timeline</h3>
                      </div>
                      <p className="text-slate-500 text-xs font-black uppercase tracking-[0.4em] pl-16">Optimized sequence of cinematic beats</p>
                    </div>
                    <div className="flex items-center gap-4 pl-16 md:pl-0">
                      <button 
                        onClick={copyAllToClipboard}
                        className="flex items-center gap-3 px-8 py-4 bg-slate-950/80 border border-white/5 text-slate-300 rounded-2xl text-xs font-black hover:bg-slate-800 hover:text-white transition-all shadow-xl"
                      >
                        <Copy className="w-4 h-4" />
                        Copy Master
                      </button>
                      <button 
                        onClick={exportToText}
                        className="flex items-center gap-3 px-8 py-4 bg-indigo-600 text-white rounded-2xl text-xs font-black hover:bg-indigo-500 hover:scale-105 transition-all shadow-2xl shadow-indigo-600/30 ring-1 ring-white/10"
                      >
                        <Download className="w-4 h-4" />
                        Export .txt
                      </button>
                    </div>
                  </div>

                  {/* Progressive Storyboard List */}
                  <div className="grid gap-16 relative">
                    {scenes.map((scene) => (
                      <SceneCard key={scene.id} scene={scene} allPages={pages} />
                    ))}
                    
                    {isGenerating && (
                      <div className="flex flex-col items-center justify-center py-24 space-y-8 animate-pulse">
                        <div className="relative">
                           <div className="w-24 h-24 border-4 border-indigo-500/10 border-t-indigo-500 rounded-full animate-spin"></div>
                           <Play className="w-8 h-8 text-indigo-500 absolute inset-0 m-auto" />
                        </div>
                        <div className="text-center space-y-2">
                           <p className="text-indigo-400 font-black tracking-[0.5em] text-xs uppercase">Synthesizing Next Beat</p>
                           <p className="text-slate-600 text-[10px] uppercase font-bold tracking-widest">Analyzing panels {genProgress.current * CHUNK_SIZE - CHUNK_SIZE + 1} to {Math.min(genProgress.current * CHUNK_SIZE, pages.length)}</p>
                        </div>
                      </div>
                    )}
                  </div>

                  {!isGenerating && (
                    <div className="glass-panel bg-gradient-to-br from-indigo-600/10 via-slate-900 to-slate-950 rounded-[4rem] p-16 sm:p-28 border border-indigo-500/10 text-center shadow-3xl">
                      <div className="w-24 h-24 bg-indigo-600 rounded-3xl flex items-center justify-center mx-auto mb-12 shadow-2xl shadow-indigo-600/40 ring-1 ring-white/20">
                          <Film className="w-12 h-12 text-white" />
                      </div>
                      <h4 className="text-5xl sm:text-6xl font-black text-white mb-8 tracking-tighter">Production Finalized.</h4>
                      <p className="text-slate-400 mb-16 max-w-2xl mx-auto text-xl leading-relaxed font-light">
                        All production beats have been analyzed and mapped. Your master script is ready for high-fidelity audio production.
                      </p>
                      <div className="flex flex-col sm:flex-row justify-center gap-6">
                        <button 
                          onClick={() => { setPages([]); setScenes([]); window.scrollTo({top: 0, behavior: 'smooth'}); }}
                          className="px-14 py-6 bg-white/5 text-white border border-white/10 rounded-[1.5rem] transition-all font-black text-lg hover:bg-white/10 hover:scale-105 active:scale-95"
                        >
                          New Session
                        </button>
                        <button 
                          onClick={exportToText}
                          className="px-14 py-6 bg-indigo-600 text-white rounded-[1.5rem] transition-all font-black text-lg hover:bg-indigo-500 hover:scale-105 active:scale-95 shadow-2xl shadow-indigo-600/20"
                        >
                          Download Script
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        ) : (
          <div className="animate-in fade-in duration-1000 space-y-24">
            {/* Visualizer Content Refined */}
            <section className="text-center space-y-10">
              <div className="inline-flex items-center gap-2 px-5 py-2 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 text-[10px] font-black uppercase tracking-[0.4em]">
                <ImageIcon className="w-4 h-4" />
                Art Concept Studio
              </div>
              <h2 className="text-6xl sm:text-8xl md:text-9xl font-black text-white leading-[0.85] tracking-tighter">
                Dream, <br className="hidden sm:block" />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-indigo-400">Illustrate.</span>
              </h2>
              <p className="text-slate-400 max-w-2xl mx-auto text-xl leading-relaxed font-light opacity-60">
                मंगा-स्टाइल आर्टवर्क तैयार करें। अपने किरदारों और दृश्यों को उच्च गुणवत्ता वाले चित्रों में बदलें।
              </p>
            </section>

            {!isApiKeySelected ? (
              <div className="glass-panel rounded-[4rem] p-16 sm:p-24 max-w-3xl mx-auto text-center shadow-3xl border border-indigo-500/10 bg-slate-950/40 relative overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 to-transparent -z-10"></div>
                <div className="w-24 h-24 bg-gradient-to-br from-indigo-600 to-purple-600 rounded-3xl flex items-center justify-center mx-auto mb-12 shadow-2xl ring-1 ring-white/20">
                  <Key className="w-12 h-12 text-white" />
                </div>
                <h3 className="text-5xl font-black text-white mb-6 tracking-tight">Access Pro Features</h3>
                <p className="text-slate-400 mb-16 text-lg leading-relaxed font-light max-w-md mx-auto">
                  High-speed image synthesis (Gemini 3 Pro) requires a project-specific API key for production-grade throughput.
                </p>
                <div className="space-y-8">
                  <button 
                    onClick={handleSelectKey}
                    className="w-full py-7 bg-indigo-600 hover:bg-indigo-500 text-white font-black text-2xl rounded-[2rem] transition-all shadow-[0_25px_50px_rgba(79,70,229,0.4)] flex items-center justify-center gap-5 ring-1 ring-white/10"
                  >
                    Authorize Studio
                    <ChevronRight className="w-7 h-7" />
                  </button>
                  <div className="flex items-center justify-center gap-8">
                    <a 
                      href="https://ai.google.dev/gemini-api/docs/billing" 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="flex items-center gap-2 text-[10px] text-slate-500 hover:text-indigo-400 transition-colors font-black uppercase tracking-widest"
                    >
                      Production Billing <ExternalLink className="w-3.5 h-3.5" />
                    </a>
                  </div>
                </div>
              </div>
            ) : (
              <div className="grid lg:grid-cols-5 gap-16 items-start">
                {/* Visualizer Side Panel */}
                <div className="lg:col-span-2 space-y-12 sticky top-32">
                  <div className="glass-panel rounded-[3rem] p-10 space-y-10 border border-white/5 bg-slate-900/40">
                    <div className="space-y-5">
                      <div className="flex items-center justify-between">
                         <label className="text-[10px] font-black text-slate-500 uppercase tracking-[0.4em] block">Concept Script</label>
                         <span className="text-[8px] font-black text-slate-700 uppercase tracking-widest">Master Key Connected</span>
                      </div>
                      <textarea 
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder="e.g. A lone swordsman standing amidst a digital graveyard of neon monoliths, cinematic backlighting, high contrast manga style."
                        className="w-full bg-slate-950 border border-white/5 rounded-[2rem] p-8 text-white placeholder:text-slate-800 focus:outline-none focus:ring-4 focus:ring-indigo-500/10 transition-all min-h-[220px] text-lg font-light leading-relaxed shadow-inner"
                      />
                    </div>

                    <div className="space-y-5">
                      <label className="text-[10px] font-black text-slate-500 uppercase tracking-[0.4em] block">Composition Ratio</label>
                      <div className="grid grid-cols-4 gap-3">
                        {ASPECT_RATIOS.map((ratio) => (
                          <button
                            key={ratio.value}
                            onClick={() => setSelectedRatio(ratio.value)}
                            title={ratio.label}
                            className={`
                              flex flex-col items-center justify-center py-5 px-2 rounded-2xl border transition-all duration-300
                              ${selectedRatio === ratio.value 
                                ? 'bg-indigo-600 border-indigo-400 text-white shadow-xl shadow-indigo-600/20 scale-105 ring-1 ring-white/10' 
                                : 'bg-slate-950 border-white/5 text-slate-600 hover:border-slate-700 hover:text-slate-300'}
                            `}
                          >
                            <span className="text-3xl mb-1.5">{ratio.icon}</span>
                            <span className="text-[8px] font-black tracking-[0.2em] uppercase">{ratio.value}</span>
                          </button>
                        ))}
                      </div>
                    </div>

                    <button
                      onClick={handleGenerateImage}
                      disabled={isGenerating || !prompt.trim()}
                      className={`
                        w-full flex items-center justify-center gap-5 py-7 rounded-[2rem] font-black text-2xl transition-all
                        ${isGenerating || !prompt.trim()
                          ? 'bg-slate-800 text-slate-700 cursor-not-allowed border border-white/5 shadow-none opacity-50' 
                          : 'bg-indigo-600 text-white hover:bg-indigo-500 hover:scale-[1.02] active:scale-95 shadow-2xl shadow-indigo-600/40 ring-1 ring-white/10'}
                      `}
                    >
                      {isGenerating ? (
                        <>
                          <Loader2 className="w-8 h-8 animate-spin" />
                          Synthesizing...
                        </>
                      ) : (
                        <>
                          <Sparkles className="w-8 h-8" />
                          Render Art
                        </>
                      )}
                    </button>
                  </div>
                  
                  {/* Credits & Info */}
                  <div className="px-6 space-y-4">
                     <p className="text-[10px] text-slate-600 leading-relaxed uppercase tracking-widest font-bold">
                       Rendered using the <span className="text-indigo-500">Imagen 4.0</span> architecture via Gemini API.
                     </p>
                  </div>
                </div>

                {/* Feed Section */}
                <div className="lg:col-span-3 space-y-16">
                   {isGenerating && (
                      <div className="glass-panel rounded-[4rem] overflow-hidden border border-indigo-500/20 shadow-3xl bg-slate-900/60 group">
                        <div className="aspect-video bg-slate-950 flex flex-col items-center justify-center gap-10 relative">
                           <div className="absolute inset-0 bg-gradient-to-t from-indigo-900/20 via-transparent to-transparent"></div>
                           <div className="relative">
                             <div className="w-24 h-24 border-4 border-indigo-500/5 border-t-indigo-500 rounded-full animate-spin"></div>
                             <ImageIcon className="w-10 h-10 text-indigo-500 absolute inset-0 m-auto opacity-40" />
                           </div>
                           <div className="text-center space-y-3">
                             <p className="text-indigo-400 font-black tracking-[0.6em] text-xs uppercase animate-pulse">Rendering Studio Grade Art</p>
                             <p className="text-slate-600 text-[9px] uppercase font-bold tracking-[0.3em]">Calibrating pixels & lighting engine...</p>
                           </div>
                        </div>
                        <div className="p-12 space-y-6">
                           <div className="h-5 w-40 bg-slate-800 rounded-full animate-pulse"></div>
                           <div className="h-4 w-full bg-slate-800 rounded-full opacity-30 animate-pulse"></div>
                        </div>
                      </div>
                    )}

                  {generatedImages.length === 0 && !isGenerating && (
                    <div className="h-[700px] flex flex-col items-center justify-center border-2 border-dashed border-white/5 rounded-[4rem] text-slate-900 space-y-10 bg-slate-950/20">
                        <div className="w-36 h-36 rounded-[3rem] border-4 border-slate-900 flex items-center justify-center opacity-30 bg-slate-900/50">
                            <ImageIcon className="w-16 h-16" />
                        </div>
                        <div className="text-center space-y-3">
                           <p className="text-3xl font-black uppercase tracking-[0.3em] opacity-20">Gallery Empty</p>
                           <p className="text-slate-700 text-xs font-black uppercase tracking-widest opacity-40">Your creative output will appear here</p>
                        </div>
                    </div>
                  )}

                  {/* Image Grid */}
                  <div className="grid grid-cols-1 gap-16">
                    {generatedImages.map((img) => (
                      <div key={img.timestamp} className="glass-panel rounded-[4.5rem] overflow-hidden group shadow-[0_40px_120px_-20px_rgba(0,0,0,0.6)] flex flex-col transition-all duration-1000 hover:scale-[1.01] border border-white/5 bg-slate-950">
                        <div className="relative flex items-center justify-center overflow-hidden bg-slate-900">
                           <img 
                            src={img.url} 
                            alt={img.prompt} 
                            className="w-full h-auto object-cover transition-transform group-hover:scale-105 duration-1000" 
                           />
                           
                           {/* Quick Action Overlay */}
                           <div className="absolute top-10 right-10 flex gap-4 opacity-0 group-hover:opacity-100 transition-all duration-500 transform translate-y-6 group-hover:translate-y-0">
                              <a 
                                href={img.url} 
                                download={`studio-output-${img.timestamp}.png`}
                                className="p-5 bg-white text-slate-950 rounded-[2rem] hover:scale-110 active:scale-90 transition-all shadow-3xl flex items-center gap-3 font-black text-xs ring-4 ring-white/10"
                                title="Download Asset"
                              >
                                <Download className="w-6 h-6" />
                                <span className="hidden sm:inline">DOWNLOAD</span>
                              </a>
                           </div>
                           
                           {/* Format Info Badge */}
                           <div className="absolute bottom-10 left-10 flex items-center gap-4 bg-black/80 backdrop-blur-3xl px-8 py-4 rounded-[2rem] border border-white/10 opacity-0 group-hover:opacity-100 transition-all duration-700 transform -translate-y-6 group-hover:translate-y-0 shadow-2xl">
                              <span className="text-[10px] font-black text-indigo-400 uppercase tracking-[0.4em]">{img.aspectRatio} Cinema Preset</span>
                           </div>
                        </div>
                        
                        {/* Artwork Metadata */}
                        <div className="p-12 sm:p-16 space-y-8 bg-slate-950/40">
                          <div className="space-y-4">
                             <span className="text-[10px] font-black text-indigo-500 uppercase tracking-widest block">Original Prompt</span>
                             <p className="text-slate-100 text-2xl lg:text-3xl leading-relaxed font-light italic">
                               "{img.prompt}"
                             </p>
                          </div>
                          <div className="flex items-center gap-8 pt-4 border-t border-white/5">
                             <div className="flex items-center gap-3">
                               <div className="w-2 h-2 rounded-full bg-indigo-500 shadow-[0_0_8px_rgba(99,102,241,0.8)]"></div>
                               <span className="text-[10px] text-slate-500 font-black uppercase tracking-[0.3em]">Titan-3 Pro Engine</span>
                             </div>
                             <div className="flex items-center gap-3">
                               <div className="w-2 h-2 rounded-full bg-slate-700"></div>
                               <span className="text-[10px] text-slate-500 font-black uppercase tracking-[0.3em]">{new Date(img.timestamp).toLocaleTimeString()}</span>
                             </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </main>

      {/* Modern Footer */}
      <footer className="mt-32 border-t border-white/5 py-16 px-6 bg-slate-950/40">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-10">
          <div className="flex flex-col items-center md:items-start gap-3">
            <div className="flex items-center gap-3 mb-2">
              <Film className="w-6 h-6 text-indigo-500" />
              <span className="text-xl font-black text-white uppercase tracking-tighter">Manga Katha Studio</span>
            </div>
            <p className="text-[10px] text-slate-600 font-black uppercase tracking-[0.3em]">AI-Powered Storytelling Suite v2.0</p>
          </div>
          
          <div className="flex items-center gap-10">
            <a href="#" className="text-[10px] text-slate-500 hover:text-white transition-all font-black uppercase tracking-widest">Documentation</a>
            <a href="#" className="text-[10px] text-slate-500 hover:text-white transition-all font-black uppercase tracking-widest">API Status</a>
            <a href="#" className="text-[10px] text-slate-500 hover:text-white transition-all font-black uppercase tracking-widest">Support</a>
          </div>
          
          <div className="flex items-center gap-6">
            <button className="p-3 bg-slate-900 border border-white/5 rounded-xl hover:text-white transition-all">
              <Github className="w-5 h-5" />
            </button>
            <button className="p-3 bg-slate-900 border border-white/5 rounded-xl hover:text-white transition-all">
              <Share2 className="w-5 h-5" />
            </button>
          </div>
        </div>
        <div className="max-w-7xl mx-auto mt-12 text-center text-[9px] text-slate-700 font-black uppercase tracking-[0.4em]">
          &copy; 2025 Manga Katha Creative. Built with Google Gemini Pro Engine.
        </div>
      </footer>
    </div>
  );
};

export default App;
